# title: STRUDEL
# email: strudel@lbl.gov
# description: >- # this means to ignore newlines until "baseurl:"
#  Scientific sofTware Research for User experience, Design, Engagement, and Learning

baseurl: "/strudel" # the subpath of your site, e.g. /blog
url: ""             # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
#remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
